# Default values for kernel.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: ehealthafrica/aether-producer
environment: "prod"
kernel_url: https://kernel.gather.aether-axxonet.com
debug: false
app:
  kafkaUrl: "axxonet-kafka.axxonet:9092"
  secret: producer-secrets
  db:
    user: axxonet_producer
    name: axxonet_producer
  kernel:
    url: https://kernel.gather.aether-axxonet.com
    db:
      name: axxonet_kernel
database:
  # set google sql instance name, e.g. modern-rex-207814:europe-west1:gatherdb-instance
  instance: axxonet-data-col-proj:asia-south1:axxonet-db-instance
provider:
  aws: false
  gcp: true
